//
//  libfacadexml.m
//  libfacade
//
//  This is an auto-generated file. Do not edit it directly (see Buildscripts/xsd.py).
//

char *xsd_contents =
    "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n"
    "<xs:schema xmlns:xs=\"http://www.w3.org/2001/XMLSchema\"\n"
    "           xmlns=\"https://facade.dev/2023/Facade.xsd\"\n"
    "           targetNamespace=\"https://facade.dev/2023/Facade.xsd\"\n"
    "           elementFormDefault=\"qualified\">\n"
    "    <xs:element name=\"facade\">\n"
    "        <xs:complexType>\n"
    "            <xs:sequence>\n"
    "                <xs:element name=\"apiVersion\" type=\"apiVersion\" />\n"
    "                <xs:element name=\"devices\">\n"
    "                    <xs:annotation>\n"
    "                        <xs:documentation>List of virtual devices to be populated by Facade "
    "driver.</xs:documentation>\n"
    "                    </xs:annotation>\n"
    "                    <xs:complexType>\n"
    "                        <xs:sequence>\n"
    "                            <xs:element name=\"video\"\n"
    "                                        type=\"video\"\n"
    "                                        minOccurs=\"0\"\n"
    "                                        maxOccurs=\"unbounded\" />\n"
    "                        </xs:sequence>\n"
    "                    </xs:complexType>\n"
    "                </xs:element>\n"
    "            </xs:sequence>\n"
    "        </xs:complexType>\n"
    "    </xs:element>\n"
    "    <xs:simpleType name=\"apiVersion\">\n"
    "        <xs:annotation>\n"
    "            <xs:documentation>The version of the Facade driver configuration being "
    "used.</xs:documentation>\n"
    "        </xs:annotation>\n"
    "        <xs:restriction base=\"xs:string\">\n"
    "            <xs:enumeration value=\"v1\" />\n"
    "        </xs:restriction>\n"
    "    </xs:simpleType>\n"
    "    <xs:complexType name=\"video\">\n"
    "        <xs:annotation>\n"
    "            <xs:documentation>Virtual camera</xs:documentation>\n"
    "        </xs:annotation>\n"
    "        <xs:sequence>\n"
    "            <xs:element name=\"id\" type=\"xs:simpleType\" minOccurs=\"0\" />\n"
    "            <xs:element name=\"name\">\n"
    "                <xs:simpleType>\n"
    "                    <xs:annotation>\n"
    "                        <xs:documentation>The name of this virtual "
    "camera.</xs:documentation>\n"
    "                    </xs:annotation>\n"
    "                    <xs:restriction base=\"xs:string\">\n"
    "                        <xs:pattern value=\"\\S.+\" />\n"
    "                    </xs:restriction>\n"
    "                </xs:simpleType>\n"
    "            </xs:element>\n"
    "            <xs:element name=\"width\">\n"
    "                <xs:simpleType>\n"
    "                    <xs:annotation>\n"
    "                        <xs:documentation>The width of the virtual camera frames (64px to "
    "8192px)</xs:documentation>\n"
    "                    </xs:annotation>\n"
    "                    <xs:restriction base=\"xs:unsignedInt\">\n"
    "                        <xs:minExclusive value=\"63\" />\n"
    "                        <xs:maxExclusive value=\"8193\" />\n"
    "                    </xs:restriction>\n"
    "                </xs:simpleType>\n"
    "            </xs:element>\n"
    "            <xs:element name=\"height\">\n"
    "                <xs:simpleType>\n"
    "                    <xs:annotation>\n"
    "                        <xs:documentation>The height of the virtual camera frames (64px to "
    "8192px)</xs:documentation>\n"
    "                    </xs:annotation>\n"
    "                    <xs:restriction base=\"xs:unsignedInt\">\n"
    "                        <xs:minExclusive value=\"63\" />\n"
    "                        <xs:maxExclusive value=\"8193\" />\n"
    "                    </xs:restriction>\n"
    "                </xs:simpleType>\n"
    "            </xs:element>\n"
    "            <xs:element name=\"frameRate\">\n"
    "                <xs:annotation>\n"
    "                    <xs:documentation>The frame rate of the camera feed (from 24 FPS to 120 "
    "FPS)</xs:documentation>\n"
    "                </xs:annotation>\n"
    "                <xs:simpleType>\n"
    "                    <xs:restriction base=\"xs:unsignedInt\">\n"
    "                        <xs:minExclusive value=\"23\" />\n"
    "                        <xs:maxExclusive value=\"121\" />\n"
    "                    </xs:restriction>\n"
    "                </xs:simpleType>\n"
    "            </xs:element>\n"
    "        </xs:sequence>\n"
    "    </xs:complexType>\n"
    "</xs:schema>\n";

char *facade_xsd(void) { return xsd_contents; }
